import google.generativeai as genai
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Configure the API key from the environment variable.
GOOGLE_API_KEY = os.getenv("GEMINI_API_KEY")
if not GOOGLE_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment variables. Please set it in your .env file.")

genai.configure(api_key=GOOGLE_API_KEY)

# Initialize the Gemini 2.5 Flash model.
model = genai.GenerativeModel('gemini-2.5-flash')

def get_gemini_response(full_query):
    """
    Sends a user's message to the Google Gemini model and returns the response.

    Args:
        full_query (str): The combined prompt and user message.

    Returns:
        str: The response generated by the Gemini model, or an error message.
    """
    try:
        response = model.generate_content(full_query)
        return response.text
    except Exception as e:
        return f"An error occurred: {e}"

if __name__ == '__main__':
    # This block is for testing the function directly
    test_message = "What is the capital of France?"
    print(f"Sending message: '{test_message}'")
    response = get_gemini_response(test_message)
    print(f"Gemini's response: {response}")